### ISSUE TITLE
main.cc 里面的rknn_init 报错 segmentation fault

### ISSUE THREAD

**Issue by WalterSenpai** [airockchip/rknn-toolkit2#100]
目前在RV1106 板子上开发程序，模型为 nanodet 。
onnx 转 rknn 没问题， rknn 交叉编译也没问题
但是在部署到rv1106上面的时候，报错 segmentation fault
![image](https://github.com/user-attachments/assets/3ce05e32-df71-4f57-a567-f69ed00b7518)
后经排查，是rknn_init() 这个方法报错了
请问一下这个具体是什么原因导致的

**Comment by yuyun2000** [comment]
解析匹配文件失败，是不是模型混用造成的？

**Comment by WalterSenpai** [comment]
> 解析匹配文件失败，是不是模型混用造成的？

目前使用的是rknpu2 说明文档里面的yolov5 的环境做的交叉编译，会不会是这个导致的

**Comment by yuyun2000** [comment]
环境不是问题，主要你这个config是yolo的配置，能加载你说的这个nanodet吗？

**Comment by WalterSenpai** [comment]
在onnx 转rknn 以及 在交叉编译的时候，都没有一个config文件， 并且rknn 在 toolkit 里面是可以正常推理的。 并且，在编译的时候也没报错，不太清楚是不是这个的原因导致的

**Comment by WalterSenpai** [comment]
> 环境不是问题，主要你这个config是yolo的配置，能加载你说的这个nanodet吗？

在onnx 转rknn 以及 在交叉编译的时候，都没有一个config文件， 并且rknn 在 toolkit 里面是可以正常推理的。 并且，在编译的时候也没报错，不太清楚是不是这个的原因导致的

**Comment by WalterSenpai** [comment]
> 环境不是问题，主要你这个config是yolo的配置，能加载你说的这个nanodet吗？

然后我自己写了个yolov5， 打包成onnx 后 转成 rknn， 再进行编译。 他报同样的错误

**Comment by yuyun2000** [comment]
介个我也不是很懂了  看一下rknpu的文档吧

**Comment by WalterSenpai** [comment]
后经确定，是因为onnx 和 rknn 版本不匹配导致的，将onnx 升级到15之后该问题解决
