### ISSUE TITLE
arm架构上如何调用npu

### ISSUE THREAD

**Issue by Alhambra-H** [airockchip/rknn-toolkit2#115]
请问如果是在arm架构上，如何调用npu呢？我芯片是RK3588s尝试安装rknn_toolkit2时发现whl全是x86架构的？是现在还没有发布支持arm架构的whl吗？还是我没找对地方呢？
![image](https://github.com/user-attachments/assets/821d5fe6-0d14-42dc-86cb-c6df0e1ad4c2)

**Comment by yuyun2000** [comment]
看一下lite  这个toolkit是给linux进行模型转换的

**Comment by yuyun2000** [comment]
请看quick start文档 太小白的问题不好回答

**Comment by Alhambra-H** [comment]
> 请看quick start文档 太小白的问题不好回答

好的 谢谢了哈
