### ISSUE TITLE
rknn-toolkit2 F.scaled_dot_product_attention(q, k, v)错误

### ISSUE THREAD

**Issue by zhanglaplace** [airockchip/rknn-toolkit2#123]
- 模型转化使用onnx->rknn， rk3566转换成功，rk3588失败，错误如下 
E RKNN: [11:23:05.067] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4038, shift = 0, limit: 0x1fff, value: 0x2010
D RKE RKNN: [11:23:05.808] failed to config argb mode layer!
- 经过调试，当return操作在F.scaled_dot_product_attention(q, k, v)前时没问题，但是加入这一行就会在3588上出错，可能是什么原因呢

**Comment by zhanglaplace** [comment]
> * 模型转化使用onnx->rknn， rk3566转换成功，rk3588失败，错误如下
>   E RKNN: [11:23:05.067] REGTASK: The bit width of field value exceeds the limit, target: v2, offset: 0x4038, shift = 0, limit: 0x1fff, value: 0x2010
>   D RKE RKNN: [11:23:05.808] failed to config argb mode layer!
> * 经过调试，当return操作在F.scaled_dot_product_attention(q, k, v)前时没问题，但是加入这一行就会在3588上出错，可能是什么原因呢

另外从Realease文档来看，是应该支持SDPA的操作的。这个是和3566和3588的开发板的某种差异性引起的吗、

**Comment by yuyun2000** [comment]
遇到这种问题先换版本

**Comment by zhanglaplace** [comment]
> 遇到这种问题先换版本

更新到最新版本后，模型转换成功了，但是中间的日志出现了很多E KRNN的如下日志，请问这个会有什么影响吗？
E RKNN: [13:48:46.380] REGTASK: The bit width of field value exceeds the limit, target: lite, offset: 0x1028, shift = 0, limit: 0x7ff, value: 0x800

**Comment by yuyun2000** [comment]
如果不影响精度，那么他们就不用管

**Comment by zhanglaplace** [comment]
> 如果不影响精度，那么他们就不用管

你好，这边在实际的rk3588开发板上运行了下，发现sdpa的操作损失很大, 以下为部分仿真与板的差异
另外，量化的时候是分步量化，这些操作都在cfg中指定了float16
![image](https://github.com/user-attachments/assets/2553671a-78bc-462b-952c-488120430d5b)

![image](https://github.com/user-attachments/assets/0e1bbf21-a15e-411d-8d0f-0d858ba4b2bc)

**Comment by yuyun2000** [comment]
不进行量化是不是精度也掉？ transformer不建议量化

**Comment by zhanglaplace** [comment]
> 不进行量化是不是精度也掉？ transformer不建议量化

这边模型不做量化，整体精度损失在5%以内
所以现在想的方案是attention的这个模块单独不做量化，以其中一个attention的模块为例，其中cfg的配置内
/transformers.2/self_attn/inner_attn/MatMul_1_output_0_sdpa: float16  但是出来的仿真结果
exSDPAttention] /transformers.2/self_attn/inner_attn/MatMul_1_output_0_sdpa                       0.98342 | 73.991    1.00000 | 0.1007        0.23407 | 458.46    0.58991 | 367.11
看cfg的内容还存在
/transformers.2/self_attn/inner_attn/MatMul_1_output_0_sdpa_q_matmul:和/transformers.2/self_attn/inner_attn/MatMul_1_output_0_sdpa_q_softmax: 这两个也需要指定: float16 吗？
也就是我如何在cfg中指定整体的attention模块的操作均为float16

**Comment by yuyun2000** [comment]
我已经说了，transformer模型不建议量化，混合量化也是量化

**Comment by zhanglaplace** [comment]
> 我已经说了，transformer模型不建议量化，混合量化也是量化

好的，我这边尝试下能不能绕开fuse matmul_softmax_matmul 为 sdpa的操作

**Comment by zeyutt** [comment]
@zhanglaplace 请问从训练好的模型转换为onnx的时候你使用的是哪个opset_version？这个参数会影响后续的精度。

**Comment by lmd6705** [comment]
F.scaled_dot_product_attention(q, k, v)  spda官方op文档说了channel限制是8192
