### ISSUE TITLE
模型推理问题

### ISSUE THREAD

**Issue by zhyzhyzhy123** [airockchip/rknn-toolkit2#130]
想请问一下`[rknn-toolkit2](https://github.com/airockchip/rknn-toolkit2)`是不是执行的是在板子上的CPU推理？想使用NPU的话是不是必须得用C的接口，有NPU的python的接口嘛。

**Comment by yuyun2000** [comment]
可以使用rknn lite

**Comment by ShawKai666** [comment]
使用RKNN-Toolkit2进行连板推理（设置rknn.init_runtime()的target参数，如target='rk3566'）

**Comment by zhyzhyzhy123** [comment]
> 可以使用rknn lite

谢谢您

**Comment by zhyzhyzhy123** [comment]
> 使用RKNN-Toolkit2进行连板推理（设置rknn.init_runtime()的target参数，如target='rk3566'）

谢谢您
