### ISSUE TITLE
环境配置报错

### ISSUE THREAD

**Issue by WN-Wolf** [airockchip/rknn-toolkit2#156]
![image](https://github.com/user-attachments/assets/a8faa49d-ab2a-41f1-aaf4-30fff4fdf2db)
**兄弟们，你们配置环境时有没有遇到这个报错？**
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.16.0 (from versions: 1.17.0, 1.17.1, 1.17.3, 1.18.0, 1.18.1, 1.19.0, 1.19.2)
ERROR: No matching distribution found for onnxruntime==1.16.0
我改成源里面提示的最低的版本，到后面就报错了。所以此路不通。

**网上搜的很古老的版本教程，我当时一下懵逼，找不到requirement.txt文件。。。**
强烈建议维护的老哥，更新代码的时候，记得更新使用文档啊@yuyun2000
![image](https://github.com/user-attachments/assets/3aa84e8a-5a3f-48c6-b86e-3b3e7ed12fe1)

**然后csdn上一大哥贴心写了一个教程，结果到我就不行了，rknn-toolkit2-2.2.0我已经换了好几个版本了。。。**
![image](https://github.com/user-attachments/assets/6e1b08cb-eb41-4f17-af59-8a39aefda93b)

**Comment by WN-Wolf** [comment]
真的自己都要被自己蠢哭了。。。
![image](https://github.com/user-attachments/assets/ef20d34d-fff7-4c95-8f8d-b2bdfde57f08)
我一直以为，cp38，是rk3588的简写，结果是cpython3.8版本，
然后，所有的一切的一切就开始变的丝滑了。
step1: conda create -n your_env python=3.8   # 其中指定python=3.8很重要！！！
step2: pip install -r requirements_cp38-2.1.0.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/
step3: pip install rknn_toolkit2-2.1.0+708089d1-cp38-cp38-linux_x86_64.whl -i https://pypi.tuna.tsinghua.edu.cn/simple/

**Comment by yuyun2000** [comment]
。。。
