### ISSUE TITLE
License to use for commercial applications

### ISSUE THREAD

**Issue by cao-nv** [airockchip/rknn-toolkit2#171]
Hi Rockchip dev., 
I'm planning to develop an application for device that uses  RK3568, and want to make clear the license. 
I have read LICENSE file, and couldn't find any clear statement for using components from Rockchip (conversion tools, linked libraries, headers) in this repository in commercial purpose. 
Could you  please elaborate, and if possible update the LICENSE. 
Thanks.

**Comment by zen-xingle** [comment]
Hi cao-nv,

If you are concerned about developing applications based on RKNPU-related software and hardware for commercial use, this is allowed, and many users meet this situation.

As far as I know, the current license of RKNPU-related software is similar to Apache-2.0. The license is currently provided by RK's legal department. And it needs time to figure out a clearer license statement. Thank you for your suggestion on updating the license.

**Comment by cao-nv** [comment]
> Hi cao-nv,
> 
> If you are concerned about developing applications based on RKNPU-related software and hardware for commercial use, this is allowed, and many users meet this situation.
> 
> As far as I know, the current license of RKNPU-related software is similar to Apache-2.0. The license is currently provided by RK's legal department. And it needs time to figure out a clearer license statement. Thank you for your suggestion on updating the license.

Thank you for the instant response. Now I can start the development with confidence.
