### ISSUE TITLE
板子的rknn_server需要和rknn-toolkit2一致吗？哪里有1.5.2的rknn_server？

### ISSUE THREAD

**Issue by sangsasi** [airockchip/rknn-toolkit2#175]
我通过adb wifi 连接的设备，想要检察板子上rknn模型的推理结果与onnx的是否一致，出现报错，请问需要如何解决。
报错如下：

W __init__: rknn-toolkit2 version: 1.5.2+b642f30c
--> Init runtime environment
--> Init list_devices
*************************
all device(s) with adb mode:
192.168.222.130:5555
*************************
I target set by user is: rk3568
I Check RK3568 board npu runtime version
I Starting ntp or adb, target is RK3568
I Start adb...
error: device offline
E init_runtime: Connect to Device Failure (-1), Please make sure the USB connection is normal!
E init_runtime: Catch exception when init runtime!
E init_runtime: Traceback (most recent call last):
E init_runtime:   File "rknn/api/rknn_base.py", line 2469, in rknn.api.rknn_base.RKNNBase.init_runtime
E init_runtime:   File "rknn/api/rknn_runtime.py", line 211, in rknn.api.rknn_runtime.RKNNRuntime.__init__
E init_runtime:   File "rknn/api/rknn_platform.py", line 344, in rknn.api.rknn_platform.start_ntp_or_adb
E init_runtime: Exception: Init runtime environment failed!
W If you can't handle this error, please try updating to the latest version of the toolkit2 and runtime from:
  https://eyun.baidu.com/s/3eTDMk6Y (Pwd: rknn)  Path: RK_NPU_SDK / RK_NPU_SDK_1.X.0 / develop /
  If the error still exists in the latest version, please collect the corresponding error logs and the model,
  convert script, and input data that can reproduce the problem, and then submit an issue on:
  https://redmine.rock-chips.com (Please consult our sales or FAE for the redmine account)
--> Init runtime
Init runtime environment failed!

**Comment by yuyun2000** [comment]
已经失传了，需要找有备份的人要
