### ISSUE TITLE
模型转化问题，使用rknn-toolkit2:2.1.0工具进行导出，时找不到onnx的输出头输出头

### ISSUE THREAD

**Issue by suse-chen** [airockchip/rknn-toolkit2#184]
我这个模型是yolov8-pose模型，模型输出头按照airockchip/yolov8的方法导出onnx模型，导出的模型有四个输出头，输出头的名字为数字，官方给了一个onnx模型，模型的输出头为英文，官方的onnx模型可以再rknn-toolkit2:2.1.0中找到找到，自己导出的输出头就不行，这是为什么呢？

**Comment by suse-chen** [comment]
![9f086b46-70c1-40aa-a2d0-be66bb95](https://github.com/user-attachments/assets/81fcb7bf-436c-406d-9aa4-a90c8f253ff1)
![9f086b46-70c1-40aa-a2d0-be66bb95c081](https://github.com/user-attachments/assets/74ca1efe-8679-4c1e-814b-9f40554eafb9)
![c0e7f6d8-a1f7-42ff-a40d-915b89eeea7d](https://github.com/user-attachments/assets/aaee0210-af28-45d9-8fef-c81afafac56c)

**Comment by yuyun2000** [comment]
https://github.com/airockchip/rknn_model_zoo/issues/194

**Comment by suse-chen** [comment]
W hybrid_quantization_step1: Adjust scale of bias 'model.23.cv2.2.2.bias'!
E hybrid_quantization_step1: The input name /model.22/cv4.0/cv4.0.0/act/Mul_output_0 is not exists. Please open the 'yolov8-pose.model' using netron to view the input name
W hybrid_quantization_step1: ===================== WARN(1) =====================
E rknn-toolkit2 version: 2.1.0+708089d1
E hybrid_quantization_step1: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 2061, in rknn.api.rknn_base.RKNNBase.hybrid_quantization_step1
  File "rknn/api/quantizer.py", line 300, in rknn.api.quantizer.Quantizer.save_hybrid_cfg
  File "rknn/api/quantizer.py", line 230, in rknn.api.quantizer.Quantizer._hybrid_custom
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: The input name /model.22/cv4.0/cv4.0.0/act/Mul_output_0 is not exists. Please open the 'yolov8-pose.model' using netron to view the input name

I ===================== WARN(0) =====================
E rknn-toolkit2 version: 2.1.0+708089d1
![9f086b46-70c1-40aa-a2d0-](https://github.com/user-attachments/assets/964a81b1-0c9a-4886-822d-99b8d03bedb3)
通过yuyun2000的提示进入到量化这步了，量化完成之后报上述错误，通过netron查看代码提示的yolov8-pose.model，确实没有/model.22/cv4.0/cv4.0.0/act/Mul_output_0这个输出
@yuyun2000 大佬能帮我解答一下吗？
