### ISSUE TITLE
关于主流深度学习框架的转换，是否考虑Mindspore和PaddlePaddle？

### ISSUE THREAD

**Issue by Suqier** [airockchip/rknn-toolkit2#189]
如题，是否考虑Mindspore和PaddlePaddle？提供load_mindspore和load_paddlepaddle类似的接口？

**Comment by swdee** [comment]
You can export [Mindspore](https://www.mindspore.cn/tutorial/training/zh-CN/r1.0/use/save_model.html) and [PaddlePaddle](https://github.com/PaddlePaddle/Paddle2ONNX) model as ONNX.

**Comment by yuyun2000** [comment]
是的 他说的对

**Comment by Suqier** [comment]
好的，谢谢
