### ISSUE TITLE
toolkit2.2转换yolov8s/v11s onnx 模型时报错"E build: Unsupport file #!"

### ISSUE THREAD

**Issue by rainote2020** [airockchip/rknn-toolkit2#201]
**平台A**：intel i7-13700+ Ubuntu22 + **torch2.5 + toolkit2.2-py3.10(使用--no-deps安装)** + cuda12.6
**平台B**：AMD x86 + WSL2/Ubuntu22(等同ubuntu22环境)+ **torch2.1 + toolkit2.2-py3.10** + cuda12.6
两者主要是pytorch版本不同，也就是安装toolkit2.2时有没有使用--no-deps参数 

**报错日志：**
> I rknn-toolkit2 version: 2.2.0
--> Config model
done
--> Loading model
I Loading : 100%|██████████████████████████████████████████████| 144/144 [00:00<00:00, 17895.17it/s]
done
--> Building model
I OpFusing 0: 100%|█████████████████████████████████████████████| 100/100 [00:00<00:00, 1489.12it/s]
I OpFusing 1 : 100%|█████████████████████████████████████████████| 100/100 [00:00<00:00, 488.24it/s]
I OpFusing 0 : 100%|█████████████████████████████████████████████| 100/100 [00:00<00:00, 337.96it/s]
I OpFusing 1 : 100%|█████████████████████████████████████████████| 100/100 [00:00<00:00, 282.36it/s]
I OpFusing 0 : 100%|█████████████████████████████████████████████| 100/100 [00:00<00:00, 263.12it/s]
I OpFusing 1 : 100%|█████████████████████████████████████████████| 100/100 [00:00<00:00, 246.61it/s]
I OpFusing 2 : 100%|█████████████████████████████████████████████| 100/100 [00:00<00:00, 110.11it/s]
E build: Unsupport file #!
I ===================== WARN(0) =====================
E rknn-toolkit2 version: 2.2.0
E build: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 1941, in rknn.api.rknn_base.RKNNBase.build
  File "rknn/api/graph_optimizer.py", line 2304, in rknn.api.graph_optimizer.GraphOptimizer.sparse_weight
  File "rknn/api/sparse_weight.py", line 528, in rknn.api.sparse_weight.sparse_weight
  File "rknn/api/sparse_weight.py", line 75, in rknn.api.sparse_weight._range_input
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Unsupport file #!

**备注：这个相同报错在完全不同的环境下发生了四次，并且报错都是Unsupport file：**
**第一次(平台A(torch2.5)+yolov8s自训练模型)过程描述：**
1. 在Torch2.5环境下使用yolo库训练yolov8s，并直接导出为onnx。
2. 通过--no-deps的方式在原有环境安装3.10的rknntoolkit
3. 使用example里的模板略微修改，对onnx模型进行转换。转换文件模板：[examples/yolov8/python/convert.py](https://github.com/airockchip/rknn_model_zoo/blob/333f9514dec41edf5281053bae9ffbe7221ba7d4/examples/yolov8/python/convert.py)使用参数：rk3588 i8
4. 在转换的过程中报错，其余时候都没报错。

**第二次(平台B(torch2.1)+yolov11s自训练模型)过程描述：**
1. 在Torch2.5环境下使用yolo库训练yolov11s，并直接导出为onnx。
2. 降级了原有的torch及其他环境，安装requirement文件的要求重新安装3.10的rknntoolkit。
3. 使用example里的模板略微修改，对onnx模型进行转换。转换文件模板：[examples/yolov8/python/convert.py](https://github.com/airockchip/rknn_model_zoo/blob/333f9514dec41edf5281053bae9ffbe7221ba7d4/examples/yolov8/python/convert.py)使用参数：rk3588 i8
4. 在转换的过程中报错，其余时候都没报错。（报错与上一种情况完全相同）

**第三次(平台A(torch2.5)+yolov8sExample中的模型)过程描述：**
1. 直接clone的rknn_model_zoo。进入这个example：[examples/yolov8](https://github.com/airockchip/rknn_model_zoo/tree/333f9514dec41edf5281053bae9ffbe7221ba7d4/examples/yolov8)
2. 下载该文件中指出的onnx模型[download_model.sh](https://github.com/airockchip/rknn_model_zoo/blob/333f9514dec41edf5281053bae9ffbe7221ba7d4/examples/yolov8/model/download_model.sh)
3. 简单修改使代码中的label文件名和目录中的label文件匹配。
4. 执行convert.py，参数为rk3588 i8
5. 报错略有不同，显示 "E build: Unsupport file person!"

**第四次(平台B(torch2.1)+yolov8sExample中的模型)过程描述：**
1. 将第三次测试的目录拷贝到该机器上
2. 执行convert.py，参数为rk3588 i8
3. 报错略有不同，显示 "E build: Unsupport file person!"

目前不清楚这个问题的原因，没有在资料中看到。本以为是不支持yolo11，更换yolov8后仍有相同报错。并且还在两个不同方式安装的toolkit环境下进行的测试。
另：本issue也于[rknn-toolkit2](https://github.com/airockchip/rknn-toolkit2)中发布，两者内容相同，如有不妥可以删除一份。

**Comment by yuyun2000** [comment]
恭喜!！ 又探索出了新种类的bug！

**Comment by rainote2020** [comment]
问题已解决，是我自己的错误。
`rknn.build(do_quantization=do_quant, dataset=DATASET_PATH)` 这里的dataset是需要图片，我理解为label，因此无法被识别。

此外再没有其他问题了。

**Comment by yuyun2000** [comment]
再次恭喜！
