### ISSUE TITLE
RK3588 c++ 零拷贝, 多batch的推理有demo？

### ISSUE THREAD

**Issue by FreshmanMa** [airockchip/rknn-toolkit2#205]

**Comment by zen-xingle** [comment]
建议导出模型时就导出多batch模型，随后的部署流程就和普通单batch模型流程一致，没有差异，包括零拷贝的使用。

**Comment by FreshmanMa** [comment]
> 建议导出模型时就导出多batch模型，随后的部署流程就和普通单batch模型流程一致，没有差异，包括零拷贝的使用。

感谢。 是这样的，已经完成了。

**Comment by liuqiuyuan-ai** [comment]
请问后处理怎么让结果与batch图像对应的？

**Comment by FreshmanMa** [comment]
> 请问后处理怎么让结果与batch图像对应的？

模型的输出就是 out :  2 x C x H x W， 取对应地址就可以了out 指向第一个输出的首地址，  out + 1xCxHxW指向第二个输出的首地址

**Comment by Joazs** [comment]
大佬打通多batch推理了吗？多batch后处理具体是如何实现呢？

**Comment by NewboySoCool** [comment]
转模型的时候，把batch改成2就好了。好像是这样，忘得差不多哈哈哈发自我的手机-------- 原始邮件 --------发件人： 速冻鱼蛋 ***@***.***>日期： 2026年3月11日周三 晚上9:09收件人： airockchip/rknn-toolkit2 ***@***.***>抄送： Fresh boy ***@***.***>, State change ***@***.***>主    题： Re: [airockchip/rknn-toolkit2] RK3588 c++ 零拷贝, 多batch的推理有demo？ (Issue #205)Joazs left a comment (airockchip/rknn-toolkit2#205)
大佬打通多batch推理了吗？多batch后处理具体是如何实现呢？

**Comment by Joazs** [comment]
我成功导出了batch=24的yolo11-obb模型。预处理和推理都通了。但是就是后处理不对，我添加了batch索引偏移，可是都只有第一个batch的结果是正常的，其他batch结果都是错误的。

**Comment by NewboySoCool** [comment]
感觉像batch 结果，没取对吗？

**Comment by Joazs** [comment]
是的，不知道怎么改了。

**Comment by NewboySoCool** [comment]
就把batch的结果对应起来就好了呀。 发自我的手机-------- 原始邮件 --------发件人： 速冻鱼蛋 ***@***.***>日期： 2026年3月12日周四 中午11:22收件人： airockchip/rknn-toolkit2 ***@***.***>抄送： Fresh boy ***@***.***>, State change ***@***.***>主    题： Re: [airockchip/rknn-toolkit2] RK3588 c++ 零拷贝, 多batch的推理有demo？ (Issue #205)Joazs left a comment (airockchip/rknn-toolkit2#205)
是的，不知道怎么改了。

**Comment by Joazs** [comment]
我试了两种方式，
1.在postprocess中计算batch偏移量，然后把这个偏移量加到idx索引上，head_buf就根据这个idx索引去取值。我打印了每个检测头的batch偏移量之差，发现它们差值是正确的。这种方式只有第一个batch结果是正确的，其他batch都是错误的。
2.我把每个batch单独拿出来，送入原来单batch的后处理函数。这种方式也是只有第一个batch结果是正确的，其他batch都是错误的。

你说的“把每个batch结果对应起来”，是具体怎么操作呢？

**Comment by NewboySoCool** [comment]
听你这意思，感觉是除了第一个bacth推理对了，后面都没对呀。 感觉你这样取数据也没问题呀发自我的手机-------- 原始邮件 --------发件人： 速冻鱼蛋 ***@***.***>日期： 2026年3月12日周四 下午3:07收件人： airockchip/rknn-toolkit2 ***@***.***>抄送： Fresh boy ***@***.***>, State change ***@***.***>主    题： Re: [airockchip/rknn-toolkit2] RK3588 c++ 零拷贝, 多batch的推理有demo？ (Issue #205)Joazs left a comment (airockchip/rknn-toolkit2#205)
我试了两种方式，
1.在postprocess中计算batch偏移量，然后把这个偏移量加到idx索引上，head_buf就根据这个idx索引去取值。我打印了每个检测头的batch偏移量之差，发现它们差值是正确的。这种方式只有第一个batch结果是正确的，其他batch都是错误的。
2.我把每个batch单独拿出来，送入原来单batch的后处理函数。这种方式也是只有第一个batch结果是正确的，其他batch都是错误的。
你说的“把每个batch结果对应起来”，是具体怎么操作呢？

**Comment by aTaoao** [comment]
请问您把该问题解决了吗，我使用python进行batch推理，同一组数据多次执行得到的结果也有差异
