### ISSUE TITLE
rv1106模型转换显示AveragePool count_include_pad=0, fallback to cpu

### ISSUE THREAD

**Issue by bbbbbrenn** [airockchip/rknn-toolkit2#217]
模型可以转换成功，但在板上运行时显示：
E RKNN: unsupport cpu AveragePool op, op name: AveragePool:AveragePool_25 in current, please try updating to the latest version of the toolkit2 and runtime from: https://console.zbox.filez.com/l/I00fc3 (PWD: rknn)
E RKNN: rknn fallback cpu failed

应该怎么办？

**Comment by yuyun2000** [comment]
升级rknpu的so库了吗
