### ISSUE TITLE
rknn_toolkit_lite2推理识别问题，目标识别太多

### ISSUE THREAD

**Issue by nullgogo** [airockchip/rknn-toolkit2#219]
我用rknn_model_zoo里的convert.py脚本转yolov5s_relu.onnx, 转后的yolov5s_relu.rknn部署在3588上，用rknn_toolkit_lite2 推理bus那张图片，识别结果不正常，目标太多了，如下图。
<img width="469" alt="2EE1818C812435180E758848DC5EF83C" src="https://github.com/user-attachments/assets/dfa676b4-64e0-4abf-addf-5339d9910c82">

用2.3.0版本的rknn_toolkit2在板子上推理识别正常。

<img width="344" alt="2C147A36F975A86B98306534D957C2AE" src="https://github.com/user-attachments/assets/48cb9950-b0fc-473b-8b24-bbaab7e1e6ad">

**Comment by nullgogo** [comment]
已解决

**Comment by Grantley-W** [comment]
Same issue，请问下最后如何解决的呢？
