### ISSUE TITLE
Could not find tensorflow==2.8.0 for python 3.10 venv

### ISSUE THREAD

**Issue by labintsev** [airockchip/rknn-toolkit2#48]
File requirements_cp310-2.0.0b0.txt has requirement tensorflow==2.8.0. I have python 3.10 venv and try to install dependencies:   

`(venv)$pip install -r requirements_cp310-2.0.0b0.txt` 

All packages collected correctly, but tensorflow gives an error:  

`ERROR: Could not find a version that satisfies the requirement tensorflow==2.8.0 (from versions: 2.10.0rc0, 2.10.0rc1, .... `

**Comment by labintsev** [comment]
I tried install rknn-toolkit2 on the board instead x86_64 machine.

**Comment by jersonal** [comment]
I also encountered the same problem. How did you solve this problem?

**Comment by labintsev** [comment]
Just install rknn-toolkit2 on the x86_64 machine, not on the board!

**Comment by jersonal** [comment]
> Just install rknn-toolkit2 on the x86_64 machine, not on the board!

thank you. I have also resolved it.
