### ISSUE TITLE
RK3588 inference test YOLOv7 model encountered RKNN-ERR-MODEL_INVALID issue

### ISSUE THREAD

**Issue by gaoxumustwin** [airockchip/rknn-toolkit2#60]
(py38) pi@CM3588:~/demo/yolov7$ python yolov7.py 
use anchors from 'model/anchors_yolov7.txt', which is [[[12.0, 16.0], [19.0, 36.0], [40.0, 28.0]], [[36.0, 75.0], [76.0, 55.0], [72.0, 146.0]], [[142.0, 110.0], [192.0, 243.0], [459.0, 401.0]]]
--> Init runtime environment
I RKNN: [03:29:25.252] RKNN Runtime Information: librknnrt version: 1.5.2 (c6b7b351a@2023-08-23T15:28:22)
I RKNN: [03:29:25.253] RKNN Driver Information: version: 0.9.2
E RKNN: [03:29:25.255] parseRKNN: invalid RKNN_MAGIC!
E RKNN: [03:29:25.255] parseRKNN from buffer: Invalid RKNN format!
E RKNN: [03:29:25.255] rknn_init, load model failed!
E Catch exception when init runtime!
E Traceback (most recent call last):
  File "/home/pi/archiconda3/envs/py38/lib/python3.8/site-packages/rknnlite/api/rknn_lite.py", line 149, in init_runtime
    self.rknn_runtime.build_graph(self.rknn_data, self.load_model_in_npu)
  File "rknnlite/api/rknn_runtime.py", line 921, in rknnlite.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_MODEL_INVALID

Init runtime environment failed

Has anyone encountered this problem before？

**Comment by wangzaichao** [comment]
我也遇到了 请问你解决了嘛

**Comment by gaoxumustwin** [comment]
我的问题是 我用的是windterm ssh工具 导致我的 模型下载损坏了 使用ftp下载后 模型正常了 ，最后成功执行
