### ISSUE TITLE
illegal instruction (core dumped)

### ISSUE THREAD

**Issue by jieblue** [airockchip/rknn-toolkit2#91]
docker 安装toolkit2 2.0.b0和1.6.0版本运行yolo5的demo，在build的阶段报错 illegal instruction，求解决。
![bbcfd578f3eaed778872247b9d7cd040](https://github.com/user-attachments/assets/cd624ab1-bf7c-424d-81c5-e01888a2206e)

**Comment by tunmx** [comment]
I also encountered the same issue when using a Docker image to convert models on my Mac with an M1 chip. I think this might be because running Docker containers on an ARM host is not compatible. I tried using an x86 host to do the same operation, and it was successful.
